<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="chainofresponsibility.ChainOfResponsibilityTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2019-10-07T13:39:43" hostname="ankurbrdwj" time="578.858">
  <properties/>
  <testcase name="givenOAuthProvider_whenCheckingAuthorized_thenSuccess()" classname="chainofresponsibility.ChainOfResponsibilityTest" time="70.553"/>
  <testcase name="givenSamlProvider_whenCheckingAuthorized_thenSuccess()" classname="chainofresponsibility.ChainOfResponsibilityTest" time="507.397"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
